### ISSUE TITLE
收信息时如果包含Emoji表情且编号会报错

### ISSUE THREAD

**Issue by chrysalis-jay** [zoujingli/ThinkService#6]
$this->receive = new DataArray(Tools::xml2arr($this->postxml));
pc上的微信软件没问题，ios和andorid收到的是☺，arr2json转码后会报错。

目前我的方式是直接输出不转编码，暂时没发现问题，或者可以过滤掉Emoji或转码还没测试

/**
     * 数组转xml内容
     * @param array $data
     * @return null|string|string
     */
    public static function arr2json($data)
    {
       return (($jsonData = json_encode($data)) == '[]' ? '{}' : $jsonData);
        return preg_replace_callback('/\\\\u([0-9a-f]{4})/i', function ($matches) {
            return mb_convert_encoding(pack("H*", $matches[1]), "UTF-8", "UCS-2BE");
        }, ($jsonData = json_encode($data)) == '[]' ? '{}' : $jsonData);
    }

**Comment by chrysalis-jay** [comment]
发现这么用回复的图文信息会被unicode编码，无法根本解决这个问题，暂时没做更多处理。

**Comment by chrysalis-jay** [comment]
目前发现发红包（sendRedPack） 返回 false， Tools::json_encode 需要改为 json_encode 才返回正常，应该也是这个地方的问题，具体原因不明，暂时也没有太好的解决办法

**Comment by zoujingli** [comment]
可能是编码问题

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/55770731-007a2d00-5ab8-11e9-8107-09ea3bc852cd.png)
新版本已经支持Emoji表情
